#! /bin/sh

#### AUTOSTART ####
sxhkd &
picom &
feh --bg-fill ~/Obrazy/wallpaper.jpg &
./.config/polybar/launch.sh &
setxkbmap pl &
redshift -l 50.60705:22.10381 & 
xautolock -time 10 -locker 'i3lock-fancy' &	
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5  

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#757575"
bspc config active_border_color	          "#ffffff"
bspc config focused_border_color	      "#cc0000"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a Gimp state=floating
bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Code desktop='^4'
bspc rule -a "" desktop='^5'
bspc rule -a Emacs desktop='4' state=tiled
