#!/bin/bash

VOL="$(pamixer --get-volume)"
ICON=""

if [ "${VOL}" -ge 0 ] && [ "${VOL}" -le  30 ]; then
	ICON=""
elif [ "${VOL}" -gt 30 ] && [ "${VOL}" -le 60 ]; then
	ICON=""
else
	ICON=""
fi



echo "${ICON} ${VOL}%"

