[theme]
primary = "white"
secondary = "white"
title = "#ff0000"
playing = "red"
playing_selected = "red"
highlight = "light white"
highlight_bg = "#242424"
error = "light white"
error_bg = "red"
statusbar = "white"
statusbar_progress = "#ff0000"
statusbar_bg = "#b51818"
cmdline = "light white"
cmdline_bg = "black"
