username = '21bq6xry5zmuvj2gtc3c6tsqy'
auth_type = 1
auth_data = 'QVFDRWNaZkpCQWx6ZGNuMzJGZjJzR2UtUHZTUjhsOUItTWhoLUt6Z1BPTTQ4VW4tRnV6OVVxazNZMHktc0lSNzc5OFVSQm4xNmh3NWNMc1hVTkNrdWRhaTYxOGpzQmJIcmNzTGtTUFhLTjdFWVJYRDc5MFNMMGJCX1pDaHk0U29lb0RRaWlPRkRWTlBvaHdfcnAyRzJVbzdyWlR1Y3dv'
